/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Struct to store usage data of the window
 */
export interface UsageInfo {
  memory: number
}
/**
 * Struct to store process information of the window
 */
export interface ProcessInfo {
  processId: number
  path: string
  name: string
  execName: string
}
/**
 * Struct to store position and size of the window
 */
export interface WindowPosition {
  x: number
  y: number
  width: number
  height: number
}
/**
 * Struct to store all informations of the window
 */
export interface WindowInfo {
  id: number
  os: string
  title: string
  position: WindowPosition
  info: ProcessInfo
  usage: UsageInfo
}
export function activeWindow(): WindowInfo
export function openWindows(): Array<WindowInfo>
